version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbit
    hostname: rabbit-serv
    ports:
      - "5672:5672"     
      - "15672:15672"
    volumes:
      - rabbit-data:/var/lib/rabbitmq
      - ./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_CONFIG_FILE: ${RABBITMQ_CONFIG_FILE}

volumes:
  rabbit-data:
